server:
  port: 8082

spring:
  application:
    name: fourdollar-batch
  datasource:
    url: jdbc:postgresql://localhost:10039/fourdollar
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
